# Multiple languages
gems:             ['jekyll-multiple-languages']

languages:        ['es', 'en']

fill_default_content: false

# Permalinks
permalink:        pretty
relative_permalinks: true

# Site settings
title:            Civio - Informe de Gestión 2015
title_en:         Civio - Annual report 2015
email:            raul@civio.es
description:      Civio - Informe de Gestión 2015
baseurl:          "" # the subpath of your site, e.g. /blog/
url:              "http://2015.civio.es" # "http://localhost:4000" the base hostname & protocol for your site

# Build settings
markdown:         kramdown
theme: jekyll-theme-cayman